### PR TITLE
fix: fix git dependencies comparison on bootstrap

### LINKED ISSUE #658: `melos bootstrap` should consider `path` when comparing two `GitReference`s
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

4.1.0

### Description

The `_updateDependencies` method in the `bootstrap` command checks if two `DependencyReference`s are equal to decide if it should update the dependencies of the modules:

https://github.com/invertase/melos/blob/ed826b39761039ba545d3ae7b18f491726d7ebe1/packages/melos/lib/src/commands/bootstrap.dart#L335C1-L362C1

However, the `GitReference` equals operator considers only the `url` and `ref` fields. As a consequence, if you change the path without changing the `url` or the `ref` in `melos.yaml`, the references are not going to be updated in the modules.

I actually lost some hours of work trying to understand why my references were not being updated.

Running `melos clean` before the bootstrap **does not** solves the problem.

Thus, Melos should consider the `path` field when the `DependencyReference` is a `GitReference`.

### Steps to reproduce

In any Melos project that has at least one git dependency on `melos.yaml`:

1. Run `melos bootstrap`
2. Change the reference `path` to something else
3. Run `melos bootstrap` again

### Expected behavior

The modules references should be updated accordingly to the new path.

### Screenshots

_No response_

### Additional context and comments

**Workaround:** currently, you can workaround this by changing either the `url` or the `ref` to something different (it may not exist), run `melos bootstrap`, revert the changes and run `melos bootstrap` again.

### PR DESCRIPTION
**Pull request by mateusfccp**
## Description

Fixes comparison check of `GitReference` by also comparing the `path`.

Fixes #658.

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

File: packages/melos/lib/src/commands/bootstrap.dart [hunk 1]
```diff
@@ -343,7 +351,9 @@ mixin _BootstrapMixin on _CleanMixin {
     // dependencies that have a different version specified in the workspace.
     final dependenciesToUpdate = workspaceDependencies.entries.where((entry) {
       if (!packageDependencies.containsKey(entry.key)) return false;
-      if (packageDependencies[entry.key] == entry.value) return false;
+      if (_areDependenciesEqual(packageDependencies[entry.key], entry.value)) {
```
Comment (spydon) [inline packages/melos/lib/src/commands/bootstrap.dart:354]: Can you add a `TODO` here that we should remove this when we change or upgrade pubspec dependency?

**Review by spydon — COMMENTED** [review]
Can you add a very simple test that verifies this, so that we don't get a regression later?

File: packages/melos/lib/src/commands/bootstrap.dart (hunk 1 above)
Comment (mateusfccp) [reply packages/melos/lib/src/commands/bootstrap.dart:358]: Done.

**Comment by spydon** [comment]
> Sure, but it will take a little longer, as I'm not very acquainted with this repository's tests.

Super! You've probably already found it, but if not, you might be able to get some inspiration from the existing bootstrap tests (where the new test should live too):
https://github.com/invertase/melos/blob/main/packages/melos/test/commands/bootstrap_test.dart

**Comment by spydon** [comment]
Hey again @mateusfccp!

> Do you have any idea on how can I test git cloning with the tests suit? For path, for instance, we have createTestTempDir, so that we can create temporary files that we use for testing.

Can't you do the same, but with a temporary local git repository? You should be able to use a git file path url (not a path dependency) to that temporary repository.

**Comment by mateusfccp** [comment]
@spydon 
I added a test to check for regressions. I'm not sure if this is the most straightforward way to test this, but it works. Let me know if I can improve it somehow.

**Review by spydon — APPROVED** [review]
Lgtm, I think that test is good enough

**Comment by mateusfccp** [comment]
It seems it failed on Windows and Linux, although it worked on Mac (the platform I'm working with).

The error seems to indicate that the path is not a git repository, even tho I initialized it and made a commit.

Unfortunately, I have no Linux or Window machine to debug the problem here... Do you have any idea what it could be?

**Comment by spydon** [comment]
> It seems it failed on Windows and Linux, although it worked on Mac (the platform I'm working with).
> 
> The error seems to indicate that the path is not a git repository, even tho I initialized it and made a commit.
> 
> Unfortunately, I have no Linux or Window machine to debug the problem here... Do you have any idea what it could be?

Sorry, I though I replied after reading it a few days ago!
Seems like you managed to sort it out?

**Comment by mateusfccp** [comment]
> > It seems it failed on Windows and Linux, although it worked on Mac (the platform I'm working with).
> > The error seems to indicate that the path is not a git repository, even tho I initialized it and made a commit.
> > Unfortunately, I have no Linux or Window machine to debug the problem here... Do you have any idea what it could be?
> 
> Sorry, I though I replied after reading it a few days ago! Seems like you managed to sort it out?

No, not really. I just rebased the PR...

I searched for potential differences in git between platforms, but didn't find anything relevant, so still in the darkness.

**Comment by spydon** [comment]
@mateusfccp just realized you probably can't see the CI logs?
Here's what it says:
```
   Resolving dependencies...
  -Because git_references depends on dependency from git which doesn't exist (Could not find git ref 'HEAD' (usage: git rev-list [<options>] <commit>... [--] [<path>...]
  -  limiting output:
...
  -    --bisect-all)), version solving failed.
  
  BootstrapException: Failed to install.: git_references at /home/runner/work/melos/melos/packages/melos/.dart_tool/GKWRBX/packages/git_references.
  package:melos/src/commands/bootstrap.dart 243:7  _BootstrapMixin._runPubGetForPackage
  ```

**Comment by mateusfccp** [comment]
> @mateusfccp just realized you probably can't see the CI logs?
> Here's what it says:
> ```
>    Resolving dependencies...
>   -Because git_references depends on dependency from git which doesn't exist (Could not find git ref 'HEAD' (usage: git rev-list [<options>] <commit>... [--] [<path>...]
>   -  limiting output:
> ...
>   -    --bisect-all)), version solving failed.
>   
>   BootstrapException: Failed to install.: git_references at /home/runner/work/melos/melos/packages/melos/.dart_tool/GKWRBX/packages/git_references.
>   package:melos/src/commands/bootstrap.dart 243:7  _BootstrapMixin._runPubGetForPackage
>   ```

Yes, I can see them. Like I said, this error seems to mean that the git repository was not created correctly or the commit.

I did pass through this error while writing the test, because at first I was only creating the git repository with `git init`, but I realized that to have a valid reference you have to have at least one commit, this is why I added the initial commit to the test.

This is why I think either the git initialization or the commit is failing in some weird way.

File: packages/melos/test/commands/bootstrap_test.dart [hunk 2]
```diff
@@ -146,6 +146,126 @@ Generating IntelliJ IDE files...
...
+      );
+
+      await createProject(
+        io.Directory('${temporaryGitRepository.absolute.path}/dependency2'),
+        const PubSpec(name: 'dependency'),
+      );
+
+      await io.Process.run(
+        'git',
+        ['add', '-A'],
```
Comment (spydon) [inline packages/melos/test/commands/bootstrap_test.dart:170]: Empty directories won't be added to git, maybe create an empty file in both of the directories first?

Comment (spydon) [reply packages/melos/test/commands/bootstrap_test.dart:170]: Ah right, I read `createDirectory` and not `createProject` when I read it this morning. :sweat_smile: 
The test passes locally for me too (linux), so permissions does sound like a good guess, but it doesn't look like it from the error message in the pipeline, if it doesn't fail silently earlier.

Comment (mateusfccp) [reply packages/melos/test/commands/bootstrap_test.dart:170]: I am going to try to reproduce the problem by using a container locally and running the same images. Maybe I can debug this way.

Comment (spydon) [reply packages/melos/test/commands/bootstrap_test.dart:170]: Good idea, I re-ran the failing test with GitHub debug printing, but it didn't give anything

Comment (spydon) [reply packages/melos/test/commands/bootstrap_test.dart:170]: @mateusfccp did you manage to find anything causing it?

Comment (mateusfccp) [reply packages/melos/test/commands/bootstrap_test.dart:170]: Hello, @spydon.

Sorry for the delay. I actually didn't get to reproduce the environment on my local machine. I tried to do it with `act`, but with no success.

File: packages/melos/lib/src/commands/bootstrap.dart [hunk 3]
```diff
@@ -363,7 +371,13 @@ mixin _BootstrapMixin on _CleanMixin {
     // dependencies that have a different version specified in the workspace.
     final dependenciesToUpdate = workspaceDependencies.entries.where((entry) {
       if (!packageDependencies.containsKey(entry.key)) return false;
-      if (packageDependencies[entry.key] == entry.value) return false;
+      // TODO: We may want to replace the `pubspec` dependency with something
```
Comment (spydon) [inline packages/melos/lib/src/commands/bootstrap.dart:374]: It is replaced with pubspec_parse now

Comment (mateusfccp) [reply packages/melos/lib/src/commands/bootstrap.dart:374]: Is this PR obsolete or does the big still exist? I am updating it, but I realized that the package has changed and I am not sure if it solves the problem by itself.

Comment (spydon) [reply packages/melos/lib/src/commands/bootstrap.dart:374]: I'm not sure. Can you try running `main`?

Comment (spydon) [reply packages/melos/lib/src/commands/bootstrap.dart:374]: Could you try it with Melos 6.3.0? (Will be released soon, if it isn't released yet when you read this)

Comment (spydon) [reply packages/melos/lib/src/commands/bootstrap.dart:287]: I had the same fight as you with this @mateusfccp, seemingly you can't run `git init` properly in the CI, so I'm just skipping this test in the CI and we can run it locally every now and then.
Thanks for your contribution!

**Comment by mateusfccp** [comment]
@spydon Sorry for the delay, my laptop had broken and was in the authorized service provider for the last month.

Thank you for assuming this and merging it!

**Comment by spydon** [comment]
> @spydon Sorry for the delay, my laptop had broken and was in the authorized service provider for the last month.
> 
> Thank you for assuming this and merging it!

No problem! 😊
