### PR TITLE
fix: `updateDependentsVersions` disabled with packages still mentioned in changelogs

### LINKED ISSUE #531: fix: `melos version --no-dependent-constraints` generates incorrect workspace `CHANGELOG`
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.1.0

### Description

Running `melos version --no-dependent-constraints` generates incorrect workspace CHANGELOG. 

`The packages with other changes` and `The packages with dependency updates only` sections contain packages that have not been updated.

In my case, the only updated packages are `windows_data`, `windows_devices`, `windows_foundation`, `windows_globalization`, and `windows_security` which can be seen from the screenshots that I've added.

<details><summary>CHANGELOG</summary>
<p>

# Change Log

All notable changes to this project will be documented in this file.
See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.

### Changes

---

Packages with breaking changes:

 - There are no breaking changes in this release.

Packages with other changes:

 - [`windows_data` - `v0.0.1+1`](#windows_data---v0011)
 - [`windows_devices` - `v0.0.2+1`](#windows_devices---v0021)
 - [`windows_foundation` - `v0.0.5`](#windows_foundation---v005)
 - [`windows_globalization` - `v0.0.1+1`](#windows_globalization---v0011)
 - [`windows_security` - `v0.0.2+1`](#windows_security---v0021)
 - [`windows_ui` - `v0.0.1+1`](#windows_ui---v0011)
 - [`windows_storage` - `v0.0.2+1`](#windows_storage---v0021)
 - [`windows_networking` - `v0.0.1+1`](#windows_networking---v0011)
 - [`windows_system` - `v0.0.2+1`](#windows_system---v0021)
 - [`windows_gaming` - `v0.0.1+1`](#windows_gaming---v0011)
 - [`windows_ai` - `v0.0.1+1`](#windows_ai---v0011)
 - [`windows_applicationmodel` - `v0.0.1+1`](#windows_applicationmodel---v0011)
 - [`windows_graphics` - `v0.0.2+1`](#windows_graphics---v0021)
 - [`windows_management` - `v0.0.1+1`](#windows_management---v0011)
 - [`windows_perception` - `v0.0.1+1`](#windows_perception---v0011)
 - [`windows_services` - `v0.0.1+1`](#windows_services---v0011)
 - [`windows_media` - `v0.0.1+1`](#windows_media---v0011)
 - [`windows_web` - `v0.0.1+1`](#windows_web---v0011)

Packages with dependency updates only:

> Packages listed below depend on other packages in this workspace that have had changes. Their versions have been incremented to bump the minimum dependency versions of the packages they depend upon in this project.

 - `windows_ui` - `v0.0.1+1`
 - `windows_storage` - `v0.0.2+1`
 - `windows_networking` - `v0.0.1+1`
 - `windows_system` - `v0.0.2+1`
 - `windows_gaming` - `v0.0.1+1`
 - `windows_ai` - `v0.0.1+1`
 - `windows_applicationmodel` - `v0.0.1+1`
 - `windows_graphics` - `v0.0.2+1`
 - `windows_management` - `v0.0.1+1`
 - `windows_perception` - `v0.0.1+1`
 - `windows_services` - `v0.0.1+1`
 - `windows_media` - `v0.0.1+1`
 - `windows_web` - `v0.0.1+1`

---

#### `windows_data` - `v0.0.1+1`

 - **DOCS**: update <xx>.microsoft.com URLs ([#212](https://github.com/dart-windows/dartwinrt/issues/212)). ([fbdf79f6](https://github.com/dart-windows/dartwinrt/commit/fbdf79f6a4e6fa3991ce6ed59379e260d2b734b3))

#### `windows_devices` - `v0.0.2+1`

 - **DOCS**(windows_devices): fix example link ([#207](https://github.com/dart-windows/dartwinrt/issues/207)). ([9b182ab2](https://github.com/dart-windows/dartwinrt/commit/9b182ab298b02aaf0da4ff9f784218e34740089a))

#### `windows_foundation` - `v0.0.5`

 - **FEAT**(windows_foundation): add some structs from Windows.UI namespace ([#211](https://github.com/dart-windows/dartwinrt/issues/211)). ([00ef0456](https://github.com/dart-windows/dartwinrt/commit/00ef0456506298362c67b34d82eed001a4735552))
 - **DOCS**: update <xx>.microsoft.com URLs ([#212](https://github.com/dart-windows/dartwinrt/issues/212)). ([fbdf79f6](https://github.com/dart-windows/dartwinrt/commit/fbdf79f6a4e6fa3991ce6ed59379e260d2b734b3))

#### `windows_globalization` - `v0.0.1+1`

 - **DOCS**: update <xx>.microsoft.com URLs ([#212](https://github.com/dart-windows/dartwinrt/issues/212)). ([fbdf79f6](https://github.com/dart-windows/dartwinrt/commit/fbdf79f6a4e6fa3991ce6ed59379e260d2b734b3))

#### `windows_security` - `v0.0.2+1`

 - **DOCS**: update <xx>.microsoft.com URLs ([#212](https://github.com/dart-windows/dartwinrt/issues/212)). ([fbdf79f6](https://github.com/dart-windows/dartwinrt/commit/fbdf79f6a4e6fa3991ce6ed59379e260d2b734b3))

</p>
</details> 

### Steps to reproduce

In a monorepo containing a minimum of two packages, where one package depends on another:
1. Run `melos version --no-dependent-constraints` and see the terminal output and the generated workspace CHANGELOG.

### Expected behavior

When running `melos version --no-dependent-constraints`, Melos should provide accurate information about the number of packages that will be updated in the terminal output. Additionally, it should not include the packages that have not been updated in the workspace CHANGELOG.

### Screenshots

terminal
gitkraken

### Additional context and comments

I think this for loop should only be executed if `updateDependentsConstraints` is `true`:
https://github.com/invertase/melos/blob/ecb4c19e8db5733ba620cea0dd0bbaa4c5243f03/packages/melos/lib/src/commands/version.dart#L264-L287

### PR DESCRIPTION
**Pull request by mzdm**
## Description

Bug description: We bumped into this while having automated release to private hosting. Consider package B has dependency on A. If A was updated and we do not want do update constraint in B nor its version (we don't want due excessive publishing because we have fully automated release process), it was still mentioned in `melos version` log that B is getting bumped and also in the workspace changelog.

Fixes #531 - But I think it should check `updateDependentsVersions` and not `updateDependentsConstraints` like in the issue. Because if we update constraint it should not reflect to changelog, right ?

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

File: packages/melos/lib/src/commands/version.dart [hunk 1]
```diff
@@ -309,10 +309,15 @@ mixin _VersionMixin on _RunMixin {
       return;
     }
 
+    final pendingPackageUpdatesCount = updateDependentsVersions
+        ? pendingPackageUpdates.length
+        : pendingPackageUpdates
+            .where((update) => update.reason != PackageUpdateReason.dependency)
+            .length;
```
Comment (spydon) [inline packages/melos/lib/src/commands/version.dart:316]: It looks to me like the `pengingPackageUpdates` should be the list that is excluding the the packages, not the count variable

Comment (mzdm) [reply packages/melos/lib/src/commands/version.dart]: Looks like that! I saw using later on `updateDependentsVersions` e.g. in `_gitCommitChanges` and thought it was for a reason but does not look like that. Tested

**Review by spydon — COMMENTED** [review]
Much better! Could you create a test for this too?

**Comment by mzdm** [comment]
> Much better! Could you create a test for this too?

Added regression test which fails on main but passes on this branch

File: packages/melos/lib/src/commands/version.dart [hunk 2]
```diff
@@ -265,6 +265,11 @@ mixin _VersionMixin on _RunMixin {
     );
 
     for (final package in dependentPackagesToVersion) {
+      // If updateDependentsVersions is set to false, we do not perform updates.
+      if (!updateDependentsVersions) {
+        continue;
+      }
```
Comment (spydon) [inline packages/melos/lib/src/commands/version.dart:271]: We don't have to go into this loop at all if `updateDependentsVersions` is false right?

**Review by spydon — APPROVED** [review]
