### PR TITLE
fix: make file IO more robust

### LINKED ISSUE #245: fix: melos bs will throw FileSystemException
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.2.1

### Description

Running `melos bs` will result in FileSystemException.
It happens right after `Linking workspace packages...`
OS: Windows

Nothing but VSCode is running. Command is executed in VSCode Terminal.
Happens also on older versions of melos.

```
Linking workspace packages...
Unhandled exception:
FileSystemException: Deletion failed, path = 'D:\_dev\[user]\endlich\.dart_tool\melos_tool' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      _CleanMixin.cleanWorkspace (package:melos/src/commands/clean.dart:30:42)
#3      _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:54:9)
<asynchronous suspension>
#4      _Melos._runLifecycle (package:melos/src/commands/runner.dart:119:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:82:5)
<asynchronous suspension>
#7      main (file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/melos-1.2.1/bin/melos.dart:10:5)
<asynchronous suspension> 
```

### Steps to reproduce

Execute `melos bs` 

### Expected behavior

... No Exception

### Screenshots

_No response_

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by blaugold**
Fixes #245

This change reorganizes file IO to go through functions
in `io.dart`. This allows us to handle issues related to
file IO in one place.

To fix intermittent failures to delete files and directories on
Windows, these operations are now retried a number of times.

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

File: packages/melos/lib/src/common/io.dart [hunk 1]
```diff
@@ -0,0 +1,288 @@
...
+    try {
+      return await resolveSymbolicLinks();
+    } on FileSystemException {
+      return null;
+    }
+  }
+}
+
+extension DirectoryUtils on Directory {
+  /// Lists the sub-directories and files of this [Directory] similar to [list].
```
Comment (nilsreichardt) [inline packages/melos/lib/src/common/io.dart:146]:
```suggestion
  /// Lists the sub-directories and files of this [Directory] similar to [list].
  ///
```

Nit: [Separate the first sentence of a doc comment into its own paragraph.](https://dart.dev/guides/language/effective-dart/documentation#do-separate-the-first-sentence-of-a-doc-comment-into-its-own-paragraph)

Comment (blaugold) [reply packages/melos/lib/src/common/io.dart:146]: Thanks :)

**Review by Salakar — APPROVED** [review]
